package br.ufpr.com.gres.changedistiller.domain;

public class DeclarationPartChange {

	private int ADDING_ATTRIBUTE_MODIFIABILITY ;
	private int REMOVING_ATTRIBUTE_MODIFIABILITY;
	private int REMOVING_CLASS_DERIVABILITY;
	private int REMOVING_METHOD_OVERRIDABILITY;
	private int ADDING_CLASS_DERIVABILITY;
	private int ADDING_METHOD_OVERRIDABILITY;
	private int total;
	
	public DeclarationPartChange() {
		ADDING_ATTRIBUTE_MODIFIABILITY = 0;
		REMOVING_ATTRIBUTE_MODIFIABILITY = 0;
		REMOVING_CLASS_DERIVABILITY  = 0;
		REMOVING_METHOD_OVERRIDABILITY = 0;
		ADDING_CLASS_DERIVABILITY = 0;
		ADDING_METHOD_OVERRIDABILITY = 0;
		total = 0;
	}

	public int getADDING_ATTRIBUTE_MODIFIABILITY() {
		return ADDING_ATTRIBUTE_MODIFIABILITY;
	}

	public void setADDING_ATTRIBUTE_MODIFIABILITY(int aDDING_ATTRIBUTE_MODIFIABILITY) {
		ADDING_ATTRIBUTE_MODIFIABILITY = aDDING_ATTRIBUTE_MODIFIABILITY;
	}

	public int getREMOVING_ATTRIBUTE_MODIFIABILITY() {
		return REMOVING_ATTRIBUTE_MODIFIABILITY;
	}

	public void setREMOVING_ATTRIBUTE_MODIFIABILITY(int rEMOVING_ATTRIBUTE_MODIFIABILITY) {
		REMOVING_ATTRIBUTE_MODIFIABILITY = rEMOVING_ATTRIBUTE_MODIFIABILITY;
	}

	public int getREMOVING_CLASS_DERIVABILITY() {
		return REMOVING_CLASS_DERIVABILITY;
	}

	public void setREMOVING_CLASS_DERIVABILITY(int rEMOVING_CLASS_DERIVABILITY) {
		REMOVING_CLASS_DERIVABILITY = rEMOVING_CLASS_DERIVABILITY;
	}

	public int getREMOVING_METHOD_OVERRIDABILITY() {
		return REMOVING_METHOD_OVERRIDABILITY;
	}

	public void setREMOVING_METHOD_OVERRIDABILITY(int rEMOVING_METHOD_OVERRIDABILITY) {
		REMOVING_METHOD_OVERRIDABILITY = rEMOVING_METHOD_OVERRIDABILITY;
	}

	public int getADDING_CLASS_DERIVABILITY() {
		return ADDING_CLASS_DERIVABILITY;
	}

	public void setADDING_CLASS_DERIVABILITY(int aDDING_CLASS_DERIVABILITY) {
		ADDING_CLASS_DERIVABILITY = aDDING_CLASS_DERIVABILITY;
	}

	public int getADDING_METHOD_OVERRIDABILITY() {
		return ADDING_METHOD_OVERRIDABILITY;
	}

	public void setADDING_METHOD_OVERRIDABILITY(int aDDING_METHOD_OVERRIDABILITY) {
		ADDING_METHOD_OVERRIDABILITY = aDDING_METHOD_OVERRIDABILITY;
	}

	public int getTotal() {
		return this.ADDING_ATTRIBUTE_MODIFIABILITY 
				+ this.ADDING_CLASS_DERIVABILITY
				+ this.ADDING_METHOD_OVERRIDABILITY
				+ this.REMOVING_ATTRIBUTE_MODIFIABILITY
				+ this.REMOVING_CLASS_DERIVABILITY
				+ this.REMOVING_METHOD_OVERRIDABILITY;
	}

	public void setTotal(int total) {
		this.total = total;
	}
	
	public  String[] getCsvDataSimple() {
	       // String[] record1 = {"ADDING_ATTRIBUTE_MODIFIABILITY","REMOVING_ATTRIBUTE_MODIFIABILITY","REMOVING_CLASS_DERIVABILITY","REMOVING_METHOD_OVERRIDABILITY","ADDING_CLASS_DERIVABILITY","ADDING_CLASS_DERIVABILITY","ADDING_METHOD_OVERRIDABILITY", "TOTAL_DECLARATIONPARTCHANGES"};
	        String[] record1 = {ADDING_ATTRIBUTE_MODIFIABILITY+"",REMOVING_ATTRIBUTE_MODIFIABILITY+"",REMOVING_CLASS_DERIVABILITY+"",REMOVING_METHOD_OVERRIDABILITY+"",ADDING_CLASS_DERIVABILITY+"",ADDING_CLASS_DERIVABILITY+"",ADDING_METHOD_OVERRIDABILITY+"",getTotal()+""};


	        return record1;
	    }

	@Override
	public String toString() {
		return "DeclarationPartChange [ADDING_ATTRIBUTE_MODIFIABILITY=" + ADDING_ATTRIBUTE_MODIFIABILITY
				+ ", REMOVING_ATTRIBUTE_MODIFIABILITY=" + REMOVING_ATTRIBUTE_MODIFIABILITY
				+ ", REMOVING_CLASS_DERIVABILITY=" + REMOVING_CLASS_DERIVABILITY + ", REMOVING_METHOD_OVERRIDABILITY="
				+ REMOVING_METHOD_OVERRIDABILITY + ", ADDING_CLASS_DERIVABILITY=" + ADDING_CLASS_DERIVABILITY
				+ ", ADDING_METHOD_OVERRIDABILITY=" + ADDING_METHOD_OVERRIDABILITY + ", total=" + getTotal() + "]";
	}
	
	
	
	
}
