package br.ufpr.com.gres.changedistiller.domain;

public class MethodDeclarationChanges {
	
	private int RETURN_TYPE_CHANGE;
	private int RETURN_TYPE_DELETE; 
	private int RETURN_TYPE_INSERT;
	private int METHOD_RENAMING; 
	private int PARAMETER_DELETE; 
	private int PARAMETER_INSERT; 
	private int PARAMETER_ORDERING_CHANGE; 
	private int PARAMETER_RENAMING; 
	private int PARAMETER_TYPE_CHANGE; 
	private int total;
	
	public MethodDeclarationChanges() {
		RETURN_TYPE_CHANGE = 0;
		RETURN_TYPE_DELETE = 0;
		RETURN_TYPE_INSERT = 0;
		METHOD_RENAMING = 0;
		PARAMETER_DELETE = 0;
		PARAMETER_INSERT = 0;
		PARAMETER_ORDERING_CHANGE = 0;
		PARAMETER_RENAMING = 0;
		PARAMETER_TYPE_CHANGE = 0;
		total = 0;
	}

	public int getRETURN_TYPE_CHANGE() {
		return RETURN_TYPE_CHANGE;
	}

	public void setRETURN_TYPE_CHANGE(int rETURN_TYPE_CHANGE) {
		RETURN_TYPE_CHANGE = rETURN_TYPE_CHANGE;
	}

	public int getRETURN_TYPE_DELETE() {
		return RETURN_TYPE_DELETE;
	}

	public void setRETURN_TYPE_DELETE(int rETURN_TYPE_DELETE) {
		RETURN_TYPE_DELETE = rETURN_TYPE_DELETE;
	}

	public int getRETURN_TYPE_INSERT() {
		return RETURN_TYPE_INSERT;
	}

	public void setRETURN_TYPE_INSERT(int rETURN_TYPE_INSERT) {
		RETURN_TYPE_INSERT = rETURN_TYPE_INSERT;
	}

	public int getMETHOD_RENAMING() {
		return METHOD_RENAMING;
	}

	public void setMETHOD_RENAMING(int mETHOD_RENAMING) {
		METHOD_RENAMING = mETHOD_RENAMING;
	}

	public int getPARAMETER_DELETE() {
		return PARAMETER_DELETE;
	}

	public void setPARAMETER_DELETE(int pARAMETER_DELETE) {
		PARAMETER_DELETE = pARAMETER_DELETE;
	}

	public int getPARAMETER_INSERT() {
		return PARAMETER_INSERT;
	}

	public void setPARAMETER_INSERT(int pARAMETER_INSERT) {
		PARAMETER_INSERT = pARAMETER_INSERT;
	}

	public int getPARAMETER_ORDERING_CHANGE() {
		return PARAMETER_ORDERING_CHANGE;
	}

	public void setPARAMETER_ORDERING_CHANGE(int pARAMETER_ORDERING_CHANGE) {
		PARAMETER_ORDERING_CHANGE = pARAMETER_ORDERING_CHANGE;
	}

	public int getPARAMETER_RENAMING() {
		return PARAMETER_RENAMING;
	}

	public void setPARAMETER_RENAMING(int pARAMETER_RENAMING) {
		PARAMETER_RENAMING = pARAMETER_RENAMING;
	}

	public int getPARAMETER_TYPE_CHANGE() {
		return PARAMETER_TYPE_CHANGE;
	}

	public void setPARAMETER_TYPE_CHANGE(int pARAMETER_TYPE_CHANGE) {
		PARAMETER_TYPE_CHANGE = pARAMETER_TYPE_CHANGE;
	}

	public int getTotal() {
		return this.METHOD_RENAMING
				+ this.PARAMETER_DELETE 
				+ this.PARAMETER_INSERT 
				+ this.PARAMETER_ORDERING_CHANGE 
				+ this.PARAMETER_RENAMING
				+ this.PARAMETER_TYPE_CHANGE
				+ this.RETURN_TYPE_CHANGE
				+ this.RETURN_TYPE_DELETE
				+ this.RETURN_TYPE_INSERT;
	}

	public void setTotal(int total) {
		this.total = total;
	}
	
	public  String[] getCsvDataSimple() {
       // String[] record1 = {"RETURN_TYPE_CHANGE","RETURN_TYPE_DELETE","RETURN_TYPE_INSERT","METHOD_RENAMING","PARAMETER_DELETE","PARAMETER_INSERT","PARAMETER_ORDERING_CHANGE","PARAMETER_RENAMING","PARAMETER_TYPE_CHANGE","TOTAL_METHODDECLARATIONSCHANGES"};
        String[] record1 = {RETURN_TYPE_CHANGE+"",RETURN_TYPE_DELETE+"",RETURN_TYPE_INSERT+"",METHOD_RENAMING+"",PARAMETER_DELETE+"",PARAMETER_INSERT+"",
        		PARAMETER_ORDERING_CHANGE+"",PARAMETER_RENAMING+"",PARAMETER_TYPE_CHANGE+"",getTotal()+""};


        return record1;
    }

	@Override
	public String toString() {
		return "MethodDeclarationChanges [RETURN_TYPE_CHANGE=" + RETURN_TYPE_CHANGE + ", RETURN_TYPE_DELETE="
				+ RETURN_TYPE_DELETE + ", RETURN_TYPE_INSERT=" + RETURN_TYPE_INSERT + ", METHOD_RENAMING="
				+ METHOD_RENAMING + ", PARAMETER_DELETE=" + PARAMETER_DELETE + ", PARAMETER_INSERT=" + PARAMETER_INSERT
				+ ", PARAMETER_ORDERING_CHANGE=" + PARAMETER_ORDERING_CHANGE + ", PARAMETER_RENAMING="
				+ PARAMETER_RENAMING + ", PARAMETER_TYPE_CHANGE=" + PARAMETER_TYPE_CHANGE + ", total=" + getTotal() + "]";
	}

	
	
	
	
	

}
